//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatherinePorras_FINBANK.Acceso_Dato.@base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KP_finbankEntities : DbContext
    {
        public KP_finbankEntities()
            : base("name=KP_finbankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SFB_AMORTIZACION> SFB_AMORTIZACION { get; set; }
        public virtual DbSet<SFB_INTERES> SFB_INTERES { get; set; }
        public virtual DbSet<SFB_SIMULACION> SFB_SIMULACION { get; set; }
        public virtual DbSet<SFB_SOLICITUD> SFB_SOLICITUD { get; set; }
        public virtual DbSet<SFB_SUCURSAL> SFB_SUCURSAL { get; set; }
        public virtual DbSet<SFB_USUARIO> SFB_USUARIO { get; set; }
    }
}
