//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatherinePorras_FINBANK.Acceso_Dato.@base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFB_SIMULACION
    {
        public int SFB_SIM_ID { get; set; }
        public Nullable<int> SFB_AMO_ID { get; set; }
        public Nullable<int> SFB_SOL_ID { get; set; }
        public Nullable<int> SFB_SUC_ID { get; set; }
        public Nullable<int> SFB_INT_ID { get; set; }
        public Nullable<int> SFB_USU_ID { get; set; }
        public Nullable<double> SFB_SIM_MONSOLICITADO { get; set; }
        public Nullable<double> SFB_SIM_PLAMESES { get; set; }
        public Nullable<double> SFB_SIM_INTANUAL { get; set; }
        public Nullable<double> SFB_SIM_CUAMENSUAL { get; set; }
        public Nullable<double> SFB_SIM_PAGTOTAL { get; set; }
    
        public virtual SFB_AMORTIZACION SFB_AMORTIZACION { get; set; }
        public virtual SFB_INTERES SFB_INTERES { get; set; }
        public virtual SFB_SOLICITUD SFB_SOLICITUD { get; set; }
        public virtual SFB_SUCURSAL SFB_SUCURSAL { get; set; }
        public virtual SFB_USUARIO SFB_USUARIO { get; set; }
    }
}
